source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'TPN_Cocos_Demo-mobile' do
  use_frameworks!

  pod 'AnyThinkiOS','6.5.73'
  pod 'AnyThinkMediationAdxSmartdigimktCNAdapter','6.5.77.2.0'
  pod 'AnyThinkDebugUISDK','1.0.8'
  pod 'Masonry'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
